name: Build Docker
on: [push]
jobs:
  build_docker_related_things:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - name: Build docker image
      run: docker build --tag frontend ${PWD}
